---
# Copyright (C) 2020-2026 Robert Wimmer
# Copyright (C) 2020-2026 Pierre Ozoux
# SPDX-License-Identifier: GPL-3.0-or-later

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

platforms:
  - name: test-wg-arch
    box: githubixx/archlinux
    memory: 1228
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.10
    groups:
      - vpn
      - archlinux
  - name: test-wg-fedora42
    box: githubixx/fedora-42
    memory: 1228
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.11
    groups:
      - vpn
      - fedora
  - name: test-wg-fedora43
    box: githubixx/fedora-43
    memory: 1228
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.12
    groups:
      - vpn
      - fedora
  - name: test-wg-debian11
    box: generic/debian11
    memory: 1228
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.13
    groups:
      - vpn
      - debian
  - name: test-wg-debian12
    box: githubixx/debian-12
    memory: 1228
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.14
    groups:
      - vpn
      - debian
  - name: test-wg-debian13
    box: githubixx/debian-13
    memory: 1228
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.15
    groups:
      - vpn
      - debian
  - name: test-wg-opensuse-leap-15-6
    box: githubixx/opensuse-leap-15.6
    memory: 1228
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.16
    groups:
      - vpn
      - opensuse
  - name: test-wg-opensuse-leap-16-0
    box: githubixx/opensuse-leap-16.0
    memory: 1228
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.17
    groups:
      - vpn
      - opensuse
  - name: test-wg-ubuntu2204
    box: githubixx/ubuntu-22.04
    memory: 1228
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.18
    groups:
      - vpn
      - ubuntu
  - name: test-wg-ubuntu2404
    box: githubixx/ubuntu-24.04
    memory: 1228
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.19
    groups:
      - vpn
      - ubuntu
  - name: test-wg-rocky9
    box: githubixx/rockylinux-9
    memory: 1228
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.20
    groups:
      - vpn
      - el
  - name: test-wg-rocky10
    box: githubixx/rockylinux-10
    memory: 1228
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.21
    groups:
      - vpn
      - el
  - name: test-wg-alma9
    box: githubixx/almalinux-9
    memory: 1228
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.22
    groups:
      - vpn
      - el
  - name: test-wg-alma10
    box: githubixx/almalinux-10
    memory: 1228
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.23
    groups:
      - vpn
      - el
  - name: test-wg-oracle9
    box: generic/oracle9
    memory: 1228
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.24
    groups:
      - vpn
      - el

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      test-wg-arch:
        wireguard_address: "10.10.10.10/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.10"
        ansible_python_interpreter: "/usr/bin/python"
      test-wg-fedora42:
        wireguard_address: "10.10.10.11/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.11"
        wireguard_interface_restart: true
      test-wg-fedora43:
        wireguard_address: "10.10.10.12/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.12"
        wireguard_interface_restart: true
      test-wg-debian11:
        wireguard_address: "10.10.10.13/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.13"
        ansible_python_interpreter: "/usr/bin/python3"
      test-wg-debian12:
        wireguard_address: "10.10.10.14/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.14"
        wireguard_conf_backup: true
        ansible_python_interpreter: "/usr/bin/python3"
      test-wg-debian13:
        wireguard_address: "10.10.10.15/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.15"
        wireguard_interface_restart: true
      test-wg-opensuse-leap-15-6:
        wireguard_address: "10.10.10.16/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.16"
        wireguard_conf_backup: true
        ansible_python_interpreter: "/usr/bin/python3.11"
      test-wg-opensuse-leap-16-0:
        wireguard_address: "10.10.10.17/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.17"
        wireguard_conf_backup: true
        ansible_python_interpreter: "/usr/bin/python3.13"
      test-wg-ubuntu2204:
        wireguard_address: "10.10.10.18/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.18"
        wireguard_conf_backup: true
      test-wg-ubuntu2404:
        wireguard_address: "10.10.10.19/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.19"
      test-wg-rocky9:
        wireguard_address: "10.10.10.20/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.20"
      test-wg-rocky10:
        wireguard_address: "10.10.10.21/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.21"
      test-wg-alma9:
        wireguard_address: "10.10.10.22/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.22"
      test-wg-alma10:
        wireguard_address: "10.10.10.23/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.23"
      test-wg-oracle9:
        wireguard_address: "10.10.10.24/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.24"

scenario:
  name: default
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
